### ISSUE TITLE
refactor bbitest to use wrapt

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#236]

**Comment by elisarver** [comment]
I've run into a number of issues with the tests even in bbitest that I think it's illustrative to explain where they fail us:

1. there are loops of testing where one input varies, and the rest stays static. That's *fine*, but if the first model in a list fails, they *all* fail without explanation as noted above. (we could also parallelize this operation with t.Parallel() to get performance gain if we weren't sharing data)
2. there are double loops, with the same situation, or only one of two of the steps repeat.
3. scenarios are initialized outside of this test loop, meaning that the initialization could be changed by calling one twice,.
4. there are a few cases where the test wouldn't report failure because someone used log.Error instead of t.Error
5. One particular test ran a big set of steps on a larger list of models, and then came back and verified only one model in the set.

**Comment by elisarver** [comment]
recentering, I'll have to fix the small, common issues first and push a set of test changes, to ensure ever-increasing confidence in these tests.

**Comment by elisarver** [comment]
made the changes in the simplest way possible; only adding `wrapt.WrapT` at the top, and modifying the test data structure validation functions to take a `*wrapt.T` instead of getting it from the test context struct. This allows us to load a dummy in and test the test helpers down the line, which is essential when something is non-trivial.

**Comment by elisarver** [comment]
removed testify after removing all instances of `assert.<Function>` and `require.<Function>` and replacing them with `t.A.Function` and `t.R.<Function>`

**Comment by elisarver** [comment]
merged changes
