### ISSUE TITLE
Pass options to nmfe

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/bbi#263]
# Summary

As a user I was to be able to pass various options to the nmfe utility

**Comment by seth127** [comment]
To be clear, we can already pass _some_ options through to `nmfe`, but I believe the request is to able to _any_ arbitrary options through to `nmfe`. Is that right?

**Comment by kyleam** [comment]
> arbitrary options through to nmfe

I suggest we don't go down that route.  nmfe isn't a fast moving target, as far as I understand, so if there are missing arguments that would be useful to add, I think we should just add them using the current approach rather than complicating both the cli interface and code with handling of arbitrary arguments.

Here's the list of nmfe options, with the ones bbi already supports checked (as of gh-280):

- [X] background
- [ ] flushtime
- [X] licfile
- [ ] locfile
- [X] maxlim
- [ ] nmexec
- [X] nobuild
- [ ] parafile
- [ ] parafprint
- [X] prcompile
- [X] prdet fault
- [X] prsame
- [ ] prseq
- [ ] rundir
- [ ] runpdir
- [ ] simparon
- [X] tprdefault
- [ ] trskip
- [ ] xmloff

@kylebaron are there any in particular that you would like to see added?  Or, if flipping it leads to a shorter list, any ones that you think should _not_ be added?

**Comment by kylebaron** [comment]
Sounds good.  We were trying to match PsN behavior and wanted to pass `prcompile`.  We must have missed that in the `print_bbi_args()` output.
