### ISSUE TITLE
bbi_init error when init bbi.yaml

### ISSUE THREAD

**Issue by yangpluszhu** [metrumresearchgroup/bbi#295]
bbi_init error when init bbi.yaml. My nonmem version is 7.4.1 with windows 10 . How to do ? Following is error message:
> bbi_init(
+   .dir=getwd(),
+   .nonmem_dir='C:/nm74g64',
+   .nonmem_version = 'nm74'
+ )
Error in bbi_init(.dir = getwd(), .nonmem_dir = "C:/nm74g64", .nonmem_version = "nm74") : 
  Must specify a valid `.nonmem_version` for bbi_init(). C:/nm74g64/examples/bbi.yaml contains the following options: ````

**Comment by kyleam** [comment]
@yangpluszhu Thanks for reporting.

Although we include Windows binaries with the bbi releases, we don't use it on Windows internally at Metrum.  We're working on setting up a Windows machine so that we can debug this issue.

[ This looks like an issue with bbi rather than bbr, so I've transferred the issue to that repo. ]

**Comment by kyleam** [comment]
@yangpluszhu The changes in #296 hopefully resolve this issue.  As I mentioned there, we still don't have a Windows machine with NONMEM, so we can't directly confirm. We're still working on that and will also be testing out these changes with a Windows user.

If you'd like to try out the dev version on your end, you can pass `.version = "v3.2.2-rc1"` to [bbr::use_bbi()](https://metrumresearchgroup.github.io/bbr/reference/use_bbi.html).  Because this is a dev version, you'll also need to set an option:

```R
options("bbr.DEV_no_min_version" = TRUE)
```
